apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookalbum2
  labels:
    app: bookalbum2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookalbum2
  template:
    metadata:
      labels:
        app: bookalbum2
    spec:
      containers:
      - name: bookalbum2
        image: sreedocker123/bookmoviealbum:latest
        ports:
        - containerPort: 80
